#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# ASUS Zenbook A14 UX3407RA factory-ACPI boot, milestone v2.0.
#
# Goal: a reproducible NO-DTB boot to the installed root filesystem and a
# multi-user console, while keeping the normal DT kernel as the rescue path.
# This intentionally reuses the last byte-for-byte reproducible, actually
# boot-tested full-ACPI kernel checkpoint (repo commit 74c9bd5) before we port
# the minimal infrastructure changes to Linux 7.2.
set -euo pipefail

ACTION="${1:-status}"
ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"
BASE="$ROOT/scripts/a14-full-acpi-restore-good-74c9bd5.sh"
KREL="7.1.5-a14-acpi-full0"
KERNEL="/boot/vmlinuz-$KREL"
INITRD="/boot/initrd.img-$KREL"
SNIPPET="/etc/grub.d/41_a14_acpi_v2"
SAFE_ENTRY="ASUS Zenbook A14 — ACPI v2 safe console ($KREL)"
STRICT_ENTRY="ASUS Zenbook A14 — ACPI v2 strict console ($KREL)"

say(){ printf '%s\n' "$*"; }
die(){ printf 'ERROR: %s\n' "$*" >&2; exit 1; }
need(){ command -v "$1" >/dev/null 2>&1 || die "missing command: $1"; }
need_root(){ [[ ${EUID:-$(id -u)} -eq 0 ]] || die "this action requires sudo/root"; }
need_user(){ [[ ${EUID:-$(id -u)} -ne 0 ]] || die "run this action as your normal user, not root"; }

owner_home(){
    if [[ -n "${SUDO_USER:-}" && "$SUDO_USER" != root ]]; then
        getent passwd "$SUDO_USER" | cut -d: -f6
    else
        printf '%s\n' "$HOME"
    fi
}

root_uuid(){
    local uuid src
    uuid="$(findmnt -n -o UUID / 2>/dev/null || true)"
    if [[ -z "$uuid" || "$uuid" == "-" ]]; then
        src="$(findmnt -n -o SOURCE /)"
        uuid="$(blkid -s UUID -o value "$src" 2>/dev/null || true)"
    fi
    [[ -n "$uuid" ]] || die "cannot determine root filesystem UUID"
    printf '%s\n' "$uuid"
}

preflight(){
    need findmnt; need blkid; need uname
    [[ -x "$BASE" ]] || die "missing pinned historical reproducer: $BASE"
    [[ -d /sys/firmware/efi ]] || die "system was not booted through UEFI"
    local uuid
    uuid="$(root_uuid)"
    say "A14_ACPI_V2_PREFLIGHT=PASS"
    say "running_kernel=$(uname -r)"
    say "root_uuid=$uuid"
    say "factory_acpi_tables=$([[ -d /sys/firmware/acpi/tables ]] && echo present || echo unavailable)"
    say "current_dt=$([[ -r /proc/device-tree/model ]] && tr '\0' ' ' </proc/device-tree/model || echo none)"
    say "target_kernelrelease=$KREL"
    say "target_mode=factory-acpi-no-dtb"
    say "target_userspace=multi-user.target"
    say "rescue_policy=current DT kernels remain untouched"
}

build(){
    need_user
    preflight
    say "A14_ACPI_V2_BUILD=START"
    bash "$BASE" build
    say "A14_ACPI_V2_BUILD=PASS"
}

remove_old_acpi_snippets(){
    local f
    shopt -s nullglob
    for f in /etc/grub.d/*a14_full_acpi* /etc/grub.d/41_a14_acpi_v2; do
        [[ -e "$f" || -L "$f" ]] || continue
        rm -f -- "$f"
        say "removed_old_grub_snippet=$f"
    done
    shopt -u nullglob
}

write_grub_snippet(){
    local uuid="$1"
    cat >"$SNIPPET" <<EOF
#!/bin/sh
exec tail -n +3 \$0
# Generated by scripts/a14-acpi-v2.sh.  Deliberately NO devicetree command.
menuentry '$SAFE_ENTRY' --class ubuntu --class gnu-linux --class gnu --class os {
    insmod gzio
    insmod part_gpt
    insmod ext2
    search --no-floppy --fs-uuid --set=root $uuid
    set gfxpayload=keep
    linux /boot/vmlinuz-$KREL root=UUID=$uuid ro acpi=force earlycon=efifb,ram console=tty0 loglevel=8 ignore_loglevel printk.time=1 systemd.unit=multi-user.target clk_ignore_unused pd_ignore_unused cma=128M efi=noruntime
    initrd /boot/initrd.img-$KREL
}

# Diagnostic entry: removes the two Linux power-framework hold-open arguments.
# Do not use this until the safe entry has produced a complete collector log.
menuentry '$STRICT_ENTRY' --class ubuntu --class gnu-linux --class gnu --class os {
    insmod gzio
    insmod part_gpt
    insmod ext2
    search --no-floppy --fs-uuid --set=root $uuid
    set gfxpayload=keep
    linux /boot/vmlinuz-$KREL root=UUID=$uuid ro acpi=force earlycon=efifb,ram console=tty0 loglevel=8 ignore_loglevel printk.time=1 systemd.unit=multi-user.target cma=128M efi=noruntime
    initrd /boot/initrd.img-$KREL
}
EOF
    chmod 0755 "$SNIPPET"

    grep -Fq "acpi=force" "$SNIPPET" || die "generated ACPI entry lacks acpi=force"
    grep -Fq "systemd.unit=multi-user.target" "$SNIPPET" || die "generated ACPI entry lacks safe userspace target"
    ! grep -Eq '^[[:space:]]*devicetree[[:space:]]' "$SNIPPET" || die "generated entry contains a DT load"
}

install(){
    need_root
    need update-grub; need grub-reboot; need findmnt; need blkid
    [[ -x "$BASE" ]] || die "missing historical reproducer: $BASE"
    [[ "$(uname -r)" != "$KREL" ]] || die "install from a DT/rescue kernel, not while running the target ACPI kernel"

    # The pinned script verifies Image hash/stamp, preserves same-krelease modules,
    # installs kernel+initrd, and first creates its historical unrestricted entry.
    bash "$BASE" install

    [[ -s "$KERNEL" ]] || die "target kernel missing after historical install"
    [[ -s "$INITRD" ]] || die "target initrd missing after historical install"

    local uuid
    uuid="$(root_uuid)"
    remove_old_acpi_snippets
    write_grub_snippet "$uuid"
    update-grub

    say "A14_ACPI_V2_INSTALL=PASS"
    say "kernel=$KERNEL"
    say "initrd=$INITRD"
    say "grub_snippet=$SNIPPET"
    say "hardware_dtb_loaded_by_entry=false"
    say "safe_entry=$SAFE_ENTRY"
    say "strict_entry=$STRICT_ENTRY"
    say "next_step=sudo ./scripts/a14-acpi-v2.sh arm-next"
}

arm_next(){
    need_root; need grub-reboot
    [[ -x "$SNIPPET" ]] || die "v2 GRUB snippet is not installed"
    grub-reboot "$SAFE_ENTRY"
    say "A14_ACPI_V2_NEXT_BOOT=ARMED"
    say "entry=$SAFE_ENTRY"
    say "automatic_reboot=false"
    command -v grub-editenv >/dev/null 2>&1 && grub-editenv /boot/grub/grubenv list 2>/dev/null || true
    say "Run 'sudo reboot' only when you are ready. GRUB should return to the normal default after that one boot."
}

unarm(){
    need_root
    if command -v grub-editenv >/dev/null 2>&1 && [[ -f /boot/grub/grubenv ]]; then
        grub-editenv /boot/grub/grubenv unset next_entry || true
    fi
    say "A14_ACPI_V2_NEXT_BOOT=DISARMED"
}

status(){
    say "===== A14 ACPI v2 status ====="
    say "running_kernel=$(uname -r)"
    say "cmdline=$(cat /proc/cmdline)"
    say "acpi_tables=$([[ -d /sys/firmware/acpi/tables ]] && echo present || echo absent)"
    say "device_tree_model=$([[ -r /proc/device-tree/model ]] && tr '\0' ' ' </proc/device-tree/model || echo none)"
    say "target_kernel=$([[ -s "$KERNEL" ]] && echo installed || echo missing)"
    say "target_initrd=$([[ -s "$INITRD" ]] && echo installed || echo missing)"
    say "grub_v2=$([[ -x "$SNIPPET" ]] && echo installed || echo missing)"
    if [[ -r /proc/cmdline ]] && grep -qw acpi=force /proc/cmdline; then
        say "current_boot_requested_acpi_force=true"
    else
        say "current_boot_requested_acpi_force=false"
    fi
    if [[ -d /sys/firmware/acpi/tables && ! -r /proc/device-tree/model ]]; then
        say "current_boot_classification=ACPI_ONLY"
    elif [[ -r /proc/device-tree/model ]]; then
        say "current_boot_classification=DT"
    else
        say "current_boot_classification=UNKNOWN"
    fi
}

collect(){
    need_root
    local home out
    home="$(owner_home)"
    out="${2:-$home/Downloads/a14-acpi-v2-$(date +%Y%m%d-%H%M%S).txt}"
    mkdir -p "$(dirname "$out")"
    "$ROOT/scripts/a14-acpi-v2-collect.sh" >"$out" 2>&1
    chown "${SUDO_USER:-root}:${SUDO_USER:-root}" "$out" 2>/dev/null || true
    say "A14_ACPI_V2_COLLECT=PASS"
    say "output=$out"
}

case "$ACTION" in
    preflight) preflight ;;
    build) build ;;
    install) install ;;
    arm-next) arm_next ;;
    unarm) unarm ;;
    status) status ;;
    collect) collect "$@" ;;
    *) die "usage: $0 {preflight|build|install|arm-next|unarm|status|collect [outfile]}" ;;
esac
